[build]
    functions = "functions"
    command =  "npm run build"
    publish = "build"
[[redirects]]
    from = "/api/*"
    to= "/.netlify/functions/:splat"
    status = 200
    force = true
[[plugins]]
    package = "@netlify/plugin-local-install-core"
    