[build]
    functions = "functions"
    command =  "npm run build"
    publish = "build"
[[redirects]]
    from = "/.netlify/functions/*"
    to= "/.netlify/functions/:splat"
    status = 200
    force = true

    